"""
Question database for the video-learning course builder.

The master selects the learner level and target duration.
The system selects a set of questions/prompts that help the master
plan a clear instructional video.

The questions are intentionally industry-neutral. They focus on
what to SHOW, SAY, DEMONSTRATE and EXPLAIN in an educational video.

Question fields:
    id           — unique number
    text         — question/prompt for the master
    hint         — practical video-production / teaching hint
    levels       — learner levels for which the question is suitable
    types        — knowledge types for which the question is suitable
    category     — video-teaching category
    time         — approximate answer/video time, in seconds
    priority     — 1 = essential, 2 = useful, 3 = additional
    answer_type  — "media" (video/text) or "yes_no"
    if_yes       — question IDs added when the master answers "yes"
    only_after   — question ID that must be answered "yes" first
"""

# ---------------------------------------------------------------------------
# Reference data
# ---------------------------------------------------------------------------

LEVELS = {
    "beginner": "Beginner",
    "intermediate": "Intermediate",
    "advanced": "Professional",
}

TYPES = {
    "procedure": "Step-by-step procedure",
    "practical_skill": "Practical skill",
    "decision_making": "Decision making",
    "experience": "Professional experience",
}

DURATIONS = [3, 5, 10, 15]  # minutes

# Category order = recommended order of questions in a video
CATEGORIES = {
    "goal": "Learning goal",
    "setup": "Show and setup",
    "demonstration": "Demonstration",
    "explanation": "Explanation",
    "reasoning": "Expert thinking",
    "mistake": "Common mistakes",
    "example": "Example",
    "exception": "Exceptions",
    "verification": "Checking the result",
    "video_quality": "Video clarity",
}

ALL_LEVELS = ["beginner", "intermediate", "advanced"]
ALL_TYPES = ["procedure", "practical_skill", "decision_making", "experience"]


# ---------------------------------------------------------------------------
# Questions / prompts for the master
# ---------------------------------------------------------------------------

QUESTIONS = [

    # ===================== GOAL — learning goal =====================
    {
        "id": 1,
        "text": "What should the learner be able to do after watching this video?",
        "hint": "Describe a concrete action: \"perform...\", \"set up...\", \"recognize...\" rather than \"understand...\".",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "goal",
        "time": 20,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 2,
        "text": "What is the one most important thing the learner must remember?",
        "hint": "Choose one key takeaway. A short video is easier to remember when it has a clear main point.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "goal",
        "time": 20,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 3,
        "text": "What should you avoid explaining because the learner does not need it yet?",
        "hint": "Remove background information that does not help the learner perform the task.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "goal",
        "time": 20,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== SETUP — show and setup =====================
    {
        "id": 4,
        "text": "What should you show before starting the main demonstration?",
        "hint": "Show the equipment, materials, interface or workspace the learner will see during the task.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "setup",
        "time": 30,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 5,
        "text": "Which tools, materials or controls should you show and name?",
        "hint": "Show each important item on camera instead of only naming it verbally.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill"],
        "category": "setup",
        "time": 40,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 6,
        "text": "What should the learner check before starting?",
        "hint": "Show the checks on camera and explain only the checks that matter for this task.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "setup",
        "time": 40,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 7,
        "text": "Is there anything the learner must prepare before following your demonstration?",
        "hint": "If yes, show the preparation clearly before the main action begins.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill"],
        "category": "setup",
        "time": 30,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 8,
        "text": "What safety point must be shown before the demonstration?",
        "hint": "Show the relevant safety equipment, position or precaution instead of giving only a verbal warning.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill"],
        "category": "setup",
        "time": 35,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== DEMONSTRATION — what to show =====================
    {
        "id": 9,
        "text": "Can you demonstrate the complete task from beginning to end?",
        "hint": "For beginners, let the learner see the whole process before focusing on individual details.",
        "levels": ["beginner"],
        "types": ["procedure", "practical_skill"],
        "category": "demonstration",
        "time": 120,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 10,
        "text": "What are the essential steps the learner needs to see?",
        "hint": "Choose only the steps needed to perform the task. Show each action clearly.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "demonstration",
        "time": 90,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 11,
        "text": "Which step should be shown slowly or from a closer camera angle?",
        "hint": "Use a close-up when a small movement, setting or detail is difficult to see.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "demonstration",
        "time": 45,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 12,
        "text": "What should you show while you are explaining it?",
        "hint": "Whenever possible, demonstrate the action at the same moment you describe it.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "demonstration",
        "time": 40,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 13,
        "text": "Where should the camera be positioned so the learner can clearly see the action?",
        "hint": "Think from the learner's point of view, not the person holding the camera.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "demonstration",
        "time": 30,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 14,
        "text": "Is there a part of the process that should be shown from a second angle?",
        "hint": "Use another angle only when it makes an important action easier to understand.",
        "levels": ["intermediate", "advanced"],
        "types": ["procedure", "practical_skill"],
        "category": "demonstration",
        "time": 45,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== EXPLANATION — what to say =====================
    {
        "id": 15,
        "text": "What does the learner need to know before performing this action?",
        "hint": "Give only the knowledge needed to understand the next action.",
        "levels": ["beginner"],
        "types": ALL_TYPES,
        "category": "explanation",
        "time": 40,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 16,
        "text": "Why are you performing this step this way?",
        "hint": "Explain the reason behind the action, not just the rule.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill"],
        "category": "explanation",
        "time": 40,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 17,
        "text": "What would happen if this step were skipped or done incorrectly?",
        "hint": "Show the consequence when possible. A visible consequence is easier to remember.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "explanation",
        "time": 45,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 18,
        "text": "Which professional term or concept needs a short explanation?",
        "hint": "If the learner may not know the term, explain it immediately when it appears.",
        "levels": ["beginner"],
        "types": ALL_TYPES,
        "category": "explanation",
        "time": 30,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 19,
        "text": "Which part of your explanation can be demonstrated instead of described?",
        "hint": "Replace abstract explanations with something the learner can see whenever possible.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "explanation",
        "time": 30,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== REASONING — expert thinking =====================
    {
        "id": 20,
        "text": "What do you notice first when you approach this task?",
        "hint": "Show the thing you are looking at and explain why it matters.",
        "levels": ["intermediate", "advanced"],
        "types": ["practical_skill", "decision_making"],
        "category": "reasoning",
        "time": 50,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 21,
        "text": "How do you know what to do next?",
        "hint": "Explain the visible signs, measurements, conditions or information that guide your decision.",
        "levels": ["intermediate", "advanced"],
        "types": ["practical_skill", "decision_making"],
        "category": "reasoning",
        "time": 60,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 22,
        "text": "What would an experienced professional notice that a beginner might miss?",
        "hint": "This is valuable expert knowledge. Show the detail and explain how you recognize it.",
        "levels": ["intermediate", "advanced"],
        "types": ["practical_skill", "experience"],
        "category": "reasoning",
        "time": 60,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 23,
        "text": "What signals tell you that something is going wrong?",
        "hint": "Show early warning signs before the problem becomes serious.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill", "decision_making"],
        "category": "reasoning",
        "time": 50,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 24,
        "text": "What decision would you make differently after gaining experience?",
        "hint": "Show the situation and explain what changed in your professional judgment.",
        "levels": ["advanced"],
        "types": ["decision_making", "experience"],
        "category": "reasoning",
        "time": 60,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 25,
        "text": "What is one practical tip that saves you time, effort or mistakes?",
        "hint": "Show the tip in action rather than only saying it.",
        "levels": ALL_LEVELS,
        "types": ["practical_skill", "experience"],
        "category": "reasoning",
        "time": 40,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== MISTAKE — common mistakes =====================
    {
        "id": 26,
        "text": "What is the most common mistake beginners make?",
        "hint": "Show the incorrect action and then show the correct version.",
        "levels": ["beginner"],
        "types": ["procedure", "practical_skill", "decision_making"],
        "category": "mistake",
        "time": 50,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 27,
        "text": "What mistake can happen even after someone has gained experience?",
        "hint": "Focus on mistakes caused by rushing, routine or overconfidence.",
        "levels": ["intermediate", "advanced"],
        "types": ALL_TYPES,
        "category": "mistake",
        "time": 50,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 28,
        "text": "Can you show a wrong way to do this and explain why it is wrong?",
        "hint": "Keep the demonstration safe. Immediately contrast it with the correct method.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "mistake",
        "time": 60,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 29,
        "text": "How can the learner notice this mistake by themselves?",
        "hint": "Give visible, audible or measurable signs they can check.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "mistake",
        "time": 45,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 30,
        "text": "What should the learner do if they have already made a mistake?",
        "hint": "Explain how to stop safely, assess the situation and ask for help when necessary.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill", "decision_making"],
        "category": "mistake",
        "time": 45,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== EXAMPLE — worked example =====================
    {
        "id": 31,
        "text": "Can you show one complete real-world example?",
        "hint": "Let the learner see the starting situation, your actions and the final result.",
        "levels": ["beginner", "intermediate"],
        "types": ALL_TYPES,
        "category": "example",
        "time": 120,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 32,
        "text": "Can you show the difference between a correct and incorrect result?",
        "hint": "Put the two results next to each other if possible and point out the visible differences.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill"],
        "category": "example",
        "time": 70,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 33,
        "text": "Can you demonstrate a difficult or unusual real-world case?",
        "hint": "For experienced learners, show the situation that requires judgment rather than routine actions.",
        "levels": ["advanced"],
        "types": ["decision_making", "experience", "practical_skill"],
        "category": "example",
        "time": 120,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 34,
        "text": "What changed in your approach after you gained experience?",
        "hint": "Show the old and current approach if possible.",
        "levels": ["advanced"],
        "types": ["experience"],
        "category": "example",
        "time": 60,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== EXCEPTION — exceptions =====================
    {
        "id": 35,
        "text": "What should the learner do if the normal process does not work?",
        "hint": "Give a simple safe response: what to check, when to stop and when to ask for help.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill", "decision_making"],
        "category": "exception",
        "time": 50,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 36,
        "text": "Are there situations where the usual method should not be used?",
        "hint": "If yes, show the situation and explain the alternative.",
        "levels": ["intermediate", "advanced"],
        "types": ["procedure", "practical_skill", "decision_making"],
        "category": "exception",
        "time": 15,
        "priority": 1,
        "answer_type": "yes_no",
        "if_yes": [37, 38],
        "only_after": None,
    },
    {
        "id": 37,
        "text": "Show one situation where the usual method does not work. What do you do instead?",
        "hint": "Use a concrete example and explain the condition that caused you to change your approach.",
        "levels": ["intermediate", "advanced"],
        "types": ["procedure", "practical_skill", "decision_making"],
        "category": "exception",
        "time": 90,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": 36,
    },
    {
        "id": 38,
        "text": "How can the learner recognize that this is an unusual situation?",
        "hint": "Show the warning signs that should make them stop and reconsider.",
        "levels": ["intermediate", "advanced"],
        "types": ["procedure", "practical_skill", "decision_making"],
        "category": "exception",
        "time": 50,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": 36,
    },
    {
        "id": 39,
        "text": "What is one professional exception or edge case worth showing?",
        "hint": "Choose an exception that is genuinely useful for an experienced learner.",
        "levels": ["advanced"],
        "types": ["procedure", "practical_skill", "experience"],
        "category": "exception",
        "time": 70,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== VERIFICATION — checking the result =====================
    {
        "id": 40,
        "text": "How can the learner check that the task was completed correctly?",
        "hint": "Show a simple check the learner can perform independently.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "verification",
        "time": 45,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 41,
        "text": "What should a correct result look, sound or behave like?",
        "hint": "Show the final result instead of relying only on verbal description.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "verification",
        "time": 50,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 42,
        "text": "What signs show that the result needs to be corrected or redone?",
        "hint": "Point directly to the visible or measurable signs of an incorrect result.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill"],
        "category": "verification",
        "time": 45,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 43,
        "text": "What final check would you personally never skip?",
        "hint": "Show the check and explain what problem it can prevent.",
        "levels": ["intermediate", "advanced"],
        "types": ["procedure", "practical_skill", "experience"],
        "category": "verification",
        "time": 45,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },

    # ===================== VIDEO QUALITY — making the explanation clear =====================
    {
        "id": 44,
        "text": "Is there anything in this demonstration that may be difficult to see on camera?",
        "hint": "If yes, move closer, change the angle, pause the action or show the detail separately.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "video_quality",
        "time": 30,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 45,
        "text": "Which moment should you pause or slow down for the learner?",
        "hint": "Slow down only the important action. Keep routine movements at normal speed.",
        "levels": ALL_LEVELS,
        "types": ["procedure", "practical_skill"],
        "category": "video_quality",
        "time": 25,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 46,
        "text": "Where should you use a close-up, on-screen label or visual marker?",
        "hint": "Use visual emphasis for small controls, important parts, settings or warning signs.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "video_quality",
        "time": 30,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 47,
        "text": "Is there any part that should be shown first and explained afterward?",
        "hint": "Sometimes seeing the complete action first gives the learner a useful mental picture.",
        "levels": ["beginner", "intermediate"],
        "types": ["procedure", "practical_skill"],
        "category": "video_quality",
        "time": 30,
        "priority": 2,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
    {
        "id": 48,
        "text": "Can you remove any talking that does not help the learner perform the task?",
        "hint": "Keep the video focused. Remove long introductions, unnecessary history and repeated information.",
        "levels": ALL_LEVELS,
        "types": ALL_TYPES,
        "category": "video_quality",
        "time": 20,
        "priority": 1,
        "answer_type": "media",
        "if_yes": [],
        "only_after": None,
    },
]


# ---------------------------------------------------------------------------
# Suggested duration focus
# ---------------------------------------------------------------------------
# These are guidance for the selection algorithm. They do not force a fixed
# number of questions; they define how much depth should normally be included.

DURATION_GUIDANCE = {
    3: {
        "description": "Essential demonstration: show the task, explain the key actions and one critical mistake or check.",
        "max_priority": 1,
        "preferred_categories": [
            "goal", "demonstration", "explanation", "mistake", "verification"
        ],
    },
    5: {
        "description": "Core explanation: essential demonstration plus preparation, reasoning or one useful practical tip.",
        "max_priority": 2,
        "preferred_categories": [
            "goal", "setup", "demonstration", "explanation",
            "mistake", "verification", "video_quality"
        ],
    },
    10: {
        "description": "Detailed explanation: demonstrate the process, explain why, show mistakes, examples and useful expert reasoning.",
        "max_priority": 2,
        "preferred_categories": [
            "goal", "setup", "demonstration", "explanation",
            "reasoning", "mistake", "example", "verification"
        ],
    },
    15: {
        "description": "Deep professional explanation: include detailed reasoning, examples, exceptions, edge cases and professional tips.",
        "max_priority": 3,
        "preferred_categories": [
            "goal", "setup", "demonstration", "explanation",
            "reasoning", "mistake", "example", "exception",
            "verification", "video_quality"
        ],
    },
}


# ---------------------------------------------------------------------------
# Templates for optional learner quizzes
# ---------------------------------------------------------------------------

QUIZ_TEMPLATES = {
    "goal": [
        "What should you be able to do after watching this video?",
        "What is the main thing to remember from this video?",
    ],
    "setup": [
        "What should be checked before starting?",
        "Which tool, material or control is needed first?",
    ],
    "demonstration": [
        "What should be done first?",
        "What is the correct order of the main steps?",
        "Which action should be performed in this situation?",
    ],
    "explanation": [
        "Why is this step necessary?",
        "What happens if this step is skipped?",
    ],
    "reasoning": [
        "What should you look at first?",
        "Which sign indicates that something is going wrong?",
    ],
    "mistake": [
        "What mistake is shown here?",
        "How can this mistake be avoided?",
        "What should you do after making this mistake?",
    ],
    "example": [
        "What did the master do in the example and why?",
        "What was the correct result in the example?",
    ],
    "exception": [
        "What should you do if the normal method does not work?",
        "Which sign indicates an unusual situation?",
    ],
    "verification": [
        "How can you check that the task was completed correctly?",
        "Which result should be corrected?",
    ],
    "video_quality": [
        "Which part of the demonstration needs a closer view?",
        "Which action should be slowed down or shown again?",
    ],
}
